spring:
  application:
    name: rest-with-spring-java
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rest-with-spring-java?createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=UTC
    username: joao
    password: buzatti
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: false

logging:
  level:
    #root: ERROR 
    com.github.joaovitorbuzatti: DEBUG  